
export const STANDARD_UNITS = [
  'm', 'km', 'm2', 'm3', 'kg', 'ton', 'L', 'no', 'ls', 'job', 'hr', 'day', 'wk', 'mo', 'pc', 'set', 'lot'
];

export const RESOURCE_UNITS = [
  'hr', 'day', 'wk', 'mo', 'kg', 'ton', 'm', 'km', 'm2', 'm3', 'L', 'no', 'pc', 'ls', 'job'
];

export const SEED_LIBRARY = [
  { name: "Excavator-320-07B / ST14-8TL", type: "Equipment", unit: "hr", unitPrice: 90.53, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Excavator-345B", type: "Equipment", unit: "hr", unitPrice: 222.32, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Excavator-350-06B / 349-07B", type: "Equipment", unit: "hr", unitPrice: 216.32, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Crawler Excavator - Bucket 0.6 m3", type: "Equipment", unit: "hr", unitPrice: 97.27, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Tire Excavator - Bucket 0.18 m3", type: "Equipment", unit: "hr", unitPrice: 149.08, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Jack hammer attachment", type: "Equipment", unit: "hr", unitPrice: 9.98, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "CAN attachment", type: "Equipment", unit: "hr", unitPrice: 12.48, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Backhoes Jack hammer", type: "Equipment", unit: "hr", unitPrice: 100.78, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Backhoes Bucket", type: "Equipment", unit: "hr", unitPrice: 75.35, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Wheel Loader 936", type: "Equipment", unit: "hr", unitPrice: 91.17, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Wheel Loader 950 - CAT", type: "Equipment", unit: "hr", unitPrice: 95.08, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Wheel Loader 966 - CAT", type: "Equipment", unit: "hr", unitPrice: 128.33, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Wheel Loader 5 m3", type: "Equipment", unit: "hr", unitPrice: 147.41, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Wheel Loader 4 m3", type: "Equipment", unit: "hr", unitPrice: 119.64, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Wheel Loader 3.3 m3", type: "Equipment", unit: "hr", unitPrice: 105.67, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Crawler Loader 1.7 m3", type: "Equipment", unit: "hr", unitPrice: 139.47, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Mini Loader - B CAT 0.3 m3", type: "Equipment", unit: "hr", unitPrice: 76.25, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Dozer D9", type: "Equipment", unit: "hr", unitPrice: 315.11, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Dozer D8", type: "Equipment", unit: "hr", unitPrice: 251.64, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Dozer D6", type: "Equipment", unit: "hr", unitPrice: 180.85, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Motor Grader CAT 140K", type: "Equipment", unit: "hr", unitPrice: 200.96, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Motor Grader CAT 120H", type: "Equipment", unit: "hr", unitPrice: 126.73, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Motor Grader SDLG-CHINA", type: "Equipment", unit: "hr", unitPrice: 111.20, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 400 Ton", type: "Equipment", unit: "hr", unitPrice: 875, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 300 Ton", type: "Equipment", unit: "hr", unitPrice: 735.48, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 250 Ton", type: "Equipment", unit: "hr", unitPrice: 619.57, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 200 Ton", type: "Equipment", unit: "hr", unitPrice: 487.30, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 150 Ton", type: "Equipment", unit: "hr", unitPrice: 650, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 100 Ton", type: "Equipment", unit: "hr", unitPrice: 276.01, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 80 Ton", type: "Equipment", unit: "hr", unitPrice: 222.20, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 70 Ton", type: "Equipment", unit: "hr", unitPrice: 191.50, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 60 Ton", type: "Equipment", unit: "hr", unitPrice: 163.92, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 50 Ton", type: "Equipment", unit: "hr", unitPrice: 144.49, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 30 Ton", type: "Equipment", unit: "hr", unitPrice: 137.33, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Hydraulic RT Crane - 13 Ton", type: "Equipment", unit: "hr", unitPrice: 108.84, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Crawler Crane- 250 Ton", type: "Equipment", unit: "hr", unitPrice: 366.25, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Crawler Crane- 200 Ton", type: "Equipment", unit: "hr", unitPrice: 345.97, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Crawler Crane- 100 Ton", type: "Equipment", unit: "hr", unitPrice: 195.62, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Crawler Crane- 75 Ton", type: "Equipment", unit: "hr", unitPrice: 161.94, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Fork Lift - 10 Ton", type: "Equipment", unit: "hr", unitPrice: 102.31, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Fork Lift - 8 Ton", type: "Equipment", unit: "hr", unitPrice: 94.78, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Fork Lift - 7 Ton", type: "Equipment", unit: "hr", unitPrice: 81.16, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Fork Lift - 5 Ton", type: "Equipment", unit: "hr", unitPrice: 76.12, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Fork Lift - 2 Ton", type: "Equipment", unit: "hr", unitPrice: 71.82, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Tower Crane - 16 Ton", type: "Equipment", unit: "hr", unitPrice: 99.08, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Tower Crane - 20/40 Ton", type: "Equipment", unit: "hr", unitPrice: 471.96, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Tower Crane - 20/40 Ton Jib 50m", type: "Equipment", unit: "hr", unitPrice: 802.72, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Manlift Crane 26 m", type: "Equipment", unit: "hr", unitPrice: 164.22, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Manlift Crane 22 m", type: "Equipment", unit: "hr", unitPrice: 152.21, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Flat bed 12m", type: "Equipment", unit: "hr", unitPrice: 92.17, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Dump Truck 16 m3", type: "Equipment", unit: "hr", unitPrice: 107.41, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Water tanker 5000 G", type: "Equipment", unit: "hr", unitPrice: 111.26, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Fuel tanker 10000 G", type: "Equipment", unit: "hr", unitPrice: 138.69, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Soil compactor -10 ton", type: "Equipment", unit: "hr", unitPrice: 85.14, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Asphalt Paver", type: "Equipment", unit: "hr", unitPrice: 296.29, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Concrete Pump TRUCK", type: "Equipment", unit: "hr", unitPrice: 233.77, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Air Compressor 800 CFM", type: "Equipment", unit: "hr", unitPrice: 69.75, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Welding Machine Diesel 400 Amp", type: "Equipment", unit: "hr", unitPrice: 17.70, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Bus 50 passenger", type: "Equipment", unit: "hr", unitPrice: 122.83, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "1000 KVA Generator", type: "Equipment", unit: "hr", unitPrice: 285.67, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  // Labor
  { name: "Welding Ganger", type: "Labor", unit: "hr", unitPrice: 52.69, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Certified SMAW Welder", type: "Labor", unit: "hr", unitPrice: 38.75, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Skilled Grinder", type: "Labor", unit: "hr", unitPrice: 34.03, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Pipe fitter", type: "Labor", unit: "hr", unitPrice: 29.87, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Scaffolder", type: "Labor", unit: "hr", unitPrice: 29.15, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Carpenter", type: "Labor", unit: "hr", unitPrice: 29.87, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Steel fixer", type: "Labor", unit: "hr", unitPrice: 29.87, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Unskilled Labor", type: "Labor", unit: "hr", unitPrice: 21.63, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Heavy Equipment Operator", type: "Labor", unit: "hr", unitPrice: 36.53, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  { name: "Driver", type: "Labor", unit: "hr", unitPrice: 35.99, productivity: 1, productivityUnit: "unit/day", resourceCount: 1, conversionFactor: 1 },
  // Material 
  { name: "Reinforcement Steel (RFT)", type: "Material", unit: "ton", unitPrice: 3200, consumption: 1, wastePercentage: 5, usages: 1, conversionFactor: 1 },
  { name: "Ready Mix Concrete (C35)", type: "Material", unit: "m3", unitPrice: 255, consumption: 1.05, wastePercentage: 5, usages: 1, conversionFactor: 1 },
  { name: "Hollow Block 200mm", type: "Material", unit: "pc", unitPrice: 3.5, consumption: 12.5, wastePercentage: 5, usages: 1, conversionFactor: 1 },
  { name: "Portland Cement (Bags)", type: "Material", unit: "ton", unitPrice: 243.4, consumption: 0.5, wastePercentage: 2, usages: 1, conversionFactor: 1 },
  { name: "Sub Base Material", type: "Material", unit: "m3", unitPrice: 29.7, consumption: 1.2, wastePercentage: 5, usages: 1, conversionFactor: 1 },
  { name: "Fuel (Diesel)", type: "Material", unit: "L", unitPrice: 1.79, consumption: 1, wastePercentage: 0, usages: 1, conversionFactor: 1 },
];
